"""
Meridian Demo SOP Version History
-------------------------------------
Seed version history for the Sepsis Management Protocol (SOP-ICU-001),
used as the flagship "why did this SOP change" demo. Each entry becomes a
SOPVersionRecord row; the current SOP row's `version` field (in
demo_sops.py) must match the final "current" entry here.

Research prototype - NOT for clinical use.
"""

SEPSIS_VERSION_HISTORY = [
    {
        "sop_id": "SOP-ICU-001",
        "version_number": "1.0",
        "status": "archived",
        "effective_date": "2023-06-01",
        "archived_date": "2023-11-15",
        "changed_by": "Dr. Elena Marsh",
        "changed_by_role": "Critical Care Attending",
        "approved_by": "Critical Care Committee",
        "committee_name": "Critical Care Committee",
        "committee_comment": "Initial standardization of sepsis response across ICU shifts - prior practice varied by attending.",
        "reason_for_change": "Initial standardization",
        "evidence_used": "Internal committee consensus",
        "change_category": "workflow_improvement",
        "summary_of_changes": "Original sepsis response protocol: qSOFA screening, blood cultures, antibiotics, fluid resuscitation.",
        "old_text": None,
        "new_text": "Original sepsis response protocol: qSOFA screening, blood cultures, antibiotics, fluid resuscitation.",
        "affected_sections": ["Procedure"],
        "training_required": True,
        "acknowledgment_required": True,
    },
    {
        "sop_id": "SOP-ICU-001",
        "version_number": "1.1",
        "status": "archived",
        "effective_date": "2023-11-15",
        "archived_date": "2024-08-01",
        "changed_by": "Dr. Elena Marsh",
        "changed_by_role": "Critical Care Attending",
        "approved_by": "Critical Care Committee",
        "committee_name": "Critical Care Committee",
        "committee_comment": "Blood cultures should be obtained before antibiotics when this does not delay treatment.",
        "reason_for_change": "Workflow improvement",
        "evidence_used": "Nursing workflow audit, Critical Care Committee memo",
        "change_category": "workflow_improvement",
        "summary_of_changes": "Added explicit blood-culture-timing clarification (before antibiotics, unless doing so would delay treatment) to resolve inconsistent nursing handoff practice.",
        "old_text": "Original sepsis response protocol: qSOFA screening, blood cultures, antibiotics, fluid resuscitation.",
        "new_text": "Original sepsis response protocol: qSOFA screening, blood cultures obtained BEFORE antibiotics when this does not delay treatment, antibiotics, fluid resuscitation.",
        "affected_sections": ["Procedure"],
        "training_required": False,
        "acknowledgment_required": True,
    },
    {
        "sop_id": "SOP-ICU-001",
        "version_number": "2.0",
        "status": "archived",
        "effective_date": "2024-08-01",
        "archived_date": "2025-01-15",
        "changed_by": "Infection Control Committee",
        "changed_by_role": "Committee",
        "approved_by": "Physician Reviewer / Compliance Officer",
        "committee_name": "Infection Control Committee",
        "committee_comment": "Repeat lactate measurement added for patients with elevated initial lactate, per updated external evidence on monitoring.",
        "reason_for_change": "Updated external evidence / better monitoring",
        "evidence_used": "WHO / CDC sepsis guidance, PubMed literature review",
        "change_category": "new_evidence",
        "summary_of_changes": "Added lactate repeat guidance: if initial lactate >2 mmol/L, repeat within 2-4 hours. Updated antibiotic timing target to within 1 hour of recognition.",
        "old_text": "Original sepsis response protocol: qSOFA screening, blood cultures obtained BEFORE antibiotics when this does not delay treatment, antibiotics, fluid resuscitation.",
        "new_text": "Sepsis response protocol: qSOFA screening, blood cultures obtained BEFORE antibiotics when this does not delay treatment, broad-spectrum antibiotics within 1 hour, measure lactate and repeat within 2-4 hours if >2 mmol/L, fluid resuscitation.",
        "affected_sections": ["Procedure", "Thresholds"],
        "training_required": True,
        "acknowledgment_required": True,
    },
    {
        "sop_id": "SOP-ICU-001",
        "version_number": "2.1",
        "status": "current",
        "effective_date": "2025-01-15",
        "archived_date": "",
        "changed_by": "Infection Control Committee",
        "changed_by_role": "Committee",
        "approved_by": "Physician Reviewer / Compliance Officer",
        "committee_name": "Infection Control Committee",
        "committee_comment": "Clarified reassessment criteria after initial fluid resuscitation.",
        "reason_for_change": "Safety improvement",
        "evidence_used": "Hospital committee memo, internal incident review",
        "change_category": "safety_improvement",
        "summary_of_changes": "Clarified fluid reassessment language: hemodynamic status (perfusion, capillary refill, HR, BP, urine output) must be reassessed after initial 30 mL/kg resuscitation, with MAP >=65 mmHg as the vasopressor-initiation threshold.",
        "old_text": "Sepsis response protocol: qSOFA screening, blood cultures obtained BEFORE antibiotics when this does not delay treatment, broad-spectrum antibiotics within 1 hour, measure lactate and repeat within 2-4 hours if >2 mmol/L, fluid resuscitation.",
        "new_text": "Sepsis response protocol: qSOFA screening, blood cultures obtained BEFORE antibiotics when this does not delay treatment, broad-spectrum antibiotics within 1 hour, measure lactate and repeat within 2-4 hours if >2 mmol/L, fluid resuscitation 30 mL/kg within 3 hours, then reassess hemodynamic status (perfusion, capillary refill, HR, BP, urine output) and initiate vasopressor if MAP <65 mmHg.",
        "affected_sections": ["Procedure", "Thresholds"],
        "training_required": False,
        "acknowledgment_required": True,
    },
]
